USE Day8IndexDb;
GO

-- 1. DIRTY READ
BEGIN TRAN;
UPDATE Day8Quotes SET Author = 'Author_Dirty' WHERE Id = 54321;
ROLLBACK TRAN;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Id = 54321;
COMMIT TRAN;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Id = 54321;
COMMIT TRAN;

-- 2. NON-REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Id = 54321;
SELECT * FROM Day8Quotes WHERE Id = 54321;
COMMIT TRAN;

BEGIN TRAN;
UPDATE Day8Quotes SET Author = 'Author_Updated' WHERE Id = 54321;
COMMIT TRAN;

UPDATE Day8Quotes SET Author = 'Author_321' WHERE Id = 54321;
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Id = 54321;
SELECT * FROM Day8Quotes WHERE Id = 54321;
COMMIT TRAN;

-- 3. PHANTOM READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Author = 'Author_321';
SELECT * FROM Day8Quotes WHERE Author = 'Author_321';
COMMIT TRAN;

BEGIN TRAN;
INSERT INTO Day8Quotes (Id, Author, Category, Text)
VALUES (999999, 'Author_321', 'Category_1', 'Phantom Quote');
COMMIT TRAN;

DELETE FROM Day8Quotes WHERE Id = 999999;
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
SELECT * FROM Day8Quotes WHERE Author = 'Author_321';
SELECT * FROM Day8Quotes WHERE Author = 'Author_321';
COMMIT TRAN;
